// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1d4bemoaEaQDgXDcdGb0BNIOiIMfXO0M',
    appId: '1:114473755221:web:9c23ed28eb52ec255aaadc',
    messagingSenderId: '114473755221',
    projectId: 'emi-calculator-510cf',
    authDomain: 'emi-calculator-510cf.firebaseapp.com',
    storageBucket: 'emi-calculator-510cf.firebasestorage.app',
    measurementId: 'G-E1EM8SV1JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRcIurQ4OkpPYYdkeLBg_hIo_VH-lVmY8',
    appId: '1:114473755221:android:2aefe08327e883fb5aaadc',
    messagingSenderId: '114473755221',
    projectId: 'emi-calculator-510cf',
    storageBucket: 'emi-calculator-510cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbR1cNqviRwJKbLraEDFjngnITsKEhLA',
    appId: '1:114473755221:ios:73f9b8ee2dafd2785aaadc',
    messagingSenderId: '114473755221',
    projectId: 'emi-calculator-510cf',
    storageBucket: 'emi-calculator-510cf.firebasestorage.app',
    iosBundleId: 'com.example.emiCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbR1cNqviRwJKbLraEDFjngnITsKEhLA',
    appId: '1:114473755221:ios:73f9b8ee2dafd2785aaadc',
    messagingSenderId: '114473755221',
    projectId: 'emi-calculator-510cf',
    storageBucket: 'emi-calculator-510cf.firebasestorage.app',
    iosBundleId: 'com.example.emiCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1d4bemoaEaQDgXDcdGb0BNIOiIMfXO0M',
    appId: '1:114473755221:web:8ca41968ba9de1ba5aaadc',
    messagingSenderId: '114473755221',
    projectId: 'emi-calculator-510cf',
    authDomain: 'emi-calculator-510cf.firebaseapp.com',
    storageBucket: 'emi-calculator-510cf.firebasestorage.app',
    measurementId: 'G-J27QVLP3NG',
  );
}
